server:
  port: 2021
spring:
  application:
    name: blog-learn-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://115.159.127.23:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 115.159.127.23 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码
  data:
    solr:
      host: http://115.159.127.23:8983/solr/sob_blog_core
blog.image.path: E:\\Coding\\Spring\\blogDemo\\images
blog.image.max-size: 2097152 #2m